# Generated by Django 6.0.4 on 2026-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_navbarmenu_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='🚀', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
