# Generated by Django 6.0.4 on 2026-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_summary', models.TextField(default="BharatDevops: India's premier DevOps & Cloud learning platform.", help_text='AI Bots aur LLMs ke liye site ki short summary (llm.txt content)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Keywords comma se separate karein (e.g. DevOps, Cloud, AWS)', max_length=255)),
                ('meta_description', models.TextField(help_text='Google Search ke liye site description (max 160 chars)', max_length=160)),
                ('author_name', models.CharField(default='Shivendra Yadav', max_length=100)),
                ('author_bio', models.TextField(help_text='Author ki details jo Google trust build karne ke liye use karta hai')),
                ('contact_email', models.EmailField(help_text='Official support email', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, help_text='Author ka LinkedIn profile link')),
            ],
            options={
                'verbose_name': 'Site Global Setting',
                'verbose_name_plural': 'Site Global Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
