# Generated by Django 6.0.4 on 2026-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_siteconfiguration_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section ki heading jo site par dikhegi', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Choti description (optional)')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner (Scrolling)'), ('courses', 'Courses Library (Cards)'), ('projects', 'Project List'), ('tools', 'DevOps Tools'), ('cloud', 'Cloud Problems'), ('newsletter', 'Newsletter/Community Box')], max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Kaun sa section pehle aayega (e.g. 1, 2, 3)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
