# Generated by Django 6.0.4 on 2026-04-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('solution_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevOpsTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_icon', models.CharField(default='🛠️', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={},
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(default='🚀', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('courses', 'Courses Library'), ('projects', 'Project List'), ('tools', 'DevOps Tools'), ('problems', 'Cloud Problems'), ('newsletter', 'Newsletter/Community')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navbarmenu',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='llm_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('home_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.homesection')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cloudproblem')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.devopstool')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
