# Generated by Django 6.0.4 on 2026-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_cloudproblem_devopstool_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='homesectionitem',
            name='icon',
            field=models.CharField(blank=True, default='💬', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homesectionitem',
            name='link',
            field=models.URLField(blank=True, help_text='Discord/WhatsApp ka URL', null=True),
        ),
        migrations.AddField(
            model_name='homesectionitem',
            name='title',
            field=models.CharField(blank=True, help_text='Community ka naam (e.g. Discord)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('courses', 'Courses Library'), ('projects', 'Project List'), ('tools', 'DevOps Tools'), ('problems', 'Cloud Problems'), ('community', 'Community Section'), ('newsletter', 'Newsletter Box')], max_length=50),
        ),
    ]
