# Generated by Django 6.0.4 on 2026-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_category_options_homesectionitem_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', '🚀 Hero Banner'), ('core_tools', '🔹 Core Tools'), ('containers', '🔹 Containers & Orchestration'), ('iac', '🔹 Infrastructure as Code (IaC)'), ('cicd', '🔹 CI/CD & Automation'), ('monitoring', '🔹 Monitoring & Logging'), ('databases', '🔹 Databases'), ('cloud', '🔹 Cloud Providers'), ('networking', '🔹 Networking & Security'), ('concepts', '🔹 DevOps General Concepts'), ('messaging', '🔹 Messaging & Streaming'), ('gitops', '🔹 GitOps / CD Tools'), ('secrets', '🔹 Secrets & Security'), ('service_mesh', '🔹 Service Mesh & Networking'), ('observability', '🔹 Observability (Advanced)'), ('artifacts', '🔹 Artifact & Package Management'), ('containers_adv', '🔹 Containers (Advanced)'), ('build_tools', '🔹 Build Tools'), ('os_infra', '🔹 OS & Infra Tools'), ('web_servers', '🔹 Web Servers & Proxies'), ('serverless', '🔹 Serverless & Cloud Native'), ('testing', '🔹 Testing & Quality'), ('data_eng', '🔹 Data Engineering & Workflow'), ('big_data', '🔹 Big Data & Processing'), ('mlops', '🔹 MLOps & AI Tools'), ('api_tools', '🔹 API & Backend Tools'), ('api_mgmt', '🔹 API Management & Testing'), ('queue_adv', '🔹 Queue + Streaming Advanced'), ('storage', '🔹 Storage & Object Storage'), ('obs_pro', '🔹 Observability Advanced (Pro Level)'), ('sec_adv', '🔹 Security (Advanced)'), ('platform_eng', '🔹 Platform Engineering'), ('versioning_adv', '🔹 Versioning & Artifact (Advanced)'), ('os_shell', '🔹 OS + Shell + CLI'), ('dev_tools_bonus', '🔹 Dev Tools (Bonus)'), ('data_platforms', '🔹 Modern Data Platforms'), ('data_integration', '🔹 Data Integration / ELT'), ('baas', '🔹 Modern Backend-as-a-Service'), ('feature_flags', '🔹 Feature Flags & Experimentation'), ('collaboration', '🔹 Collaboration & DevOps Tools'), ('cdn_edge', '🔹 CDN & Edge / Performance'), ('auth_identity', '🔹 Authentication & Identity'), ('payment_saas', '🔹 Payment / SaaS Infra'), ('obs_saas', '🔹 Observability SaaS'), ('community', '💬 Community Section'), ('newsletter', '📧 Newsletter Box')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(help_text='Section ka heading (e.g. Core Tools)', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='icon',
            field=models.CharField(blank=True, default='⚙️', help_text='Emoji ya Icon class', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='link',
            field=models.URLField(blank=True, help_text='Redirect link (Internal ya External)', null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='title',
            field=models.CharField(blank=True, help_text='Subject ka naam (e.g. Docker, Terraform)', max_length=255, null=True),
        ),
    ]
