# Generated by Django 6.0.4 on 2026-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_homesection_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL (e.g. https://www.youtube.com/watch?v=...)', null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='icon',
            field=models.CharField(blank=True, default='⚙️', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='link',
            field=models.URLField(blank=True, help_text='External link (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-filled if Course selected', max_length=255, null=True),
        ),
    ]
