# Generated by Django 6.0.4 on 2026-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_video_url_alter_homesectionitem_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL ke liye (e.g. linux-roadmap)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(help_text='Section ka heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL', null=True),
        ),
    ]
