# Generated by Django 6.0.4 on 2026-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_slug_alter_homesection_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lesson ka unique URL', max_length=255, null=True, unique=True),
        ),
    ]
